server:
  port: 9002
spring:
  application:
    name: spring_boot_app_docker_k8_main1
  main:
    "banner-mode": off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hplus3
    username: root
    password: pass@word1
    platform: mysql
    initialization-mode: always
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
      generate-ddl: true
      show-sql: true
